import formatImage from '../assets/questionImages/formattedTextImg.jpeg';


const htmlQuestionBank = [
    {
        question: 'How do you create the formatted text below?',
        image: formatImage,
        answers: [
            '<p> This is a <mark>Formatted</mark> text</p>',
            '<p>This is a <highlight>Formatted<highlight> text</p>',
            '<p>This is a <color>Formatted</color> text</p>',
            '<p> This is a <em>Formatted</em> text<p>',
        ],
        correct: '<p> This is a <mark>Formatted</mark> text</p>',
        explanation: '',
        questionId: '24000',
        keyword: ['HTML Tags', 'Semantic Tags'],
    },
    {
        question: 'Which group of tags are considered semantic tags',
        answers: [
            '<div>, <span>',
            '<img>, <table>, <article>, <section>, <aside>, <nav>',
        ],
        correct: '<img>, <table>, <article>, <section>, <aside>, <nav>',
        explanation: 'Semantic tags in HTML are elemetnts that clearly define their content\'s purpose and meaing to both the browswer and the developer.',
        questionId: '24001',
        keyword: ['HTML Tags', 'Semantic Tags'],
    },
    {
        question: 'What are semantic tags in HTML',
        answers: [
            'Semantic tags in HTML are tags that don\'t care about the semantics.',
            'Semantic tags are tags like the <div> and <span> tags.',
            'Semantic tags in HTML are elemetnts that clearly define their content\'s purpose and meaing to both the browswer and the developer.',
            'Semantic tags are the tags used to process the inputs of a form.',
        ],
        correct: 'Semantic tags in HTML are elemetnts that clearly define their content\'s purpose and meaing to both the browswer and the developer.',
        explanation: '',
        questionId: '24002',
        keyword: ['HTML Tags', 'Semantic Tags'],
    },

    {
        question: 'There are two divs, they are next to each other, and I need to increase the space between the divs. Would I use margin or padding?',
        answers: [
            'Padding, because padding increases space outside of an element, and that would apply in this scenario.',
            'Space, using space: 1 on the div will increase the space between the divs by 1rem.',
            'Widen Right, using the widen_right: 1 will increase the space between the divs by 16px.',
            'Margin, because margin increases space outside of an element, and that would apply in this scenario.',
        ],
        correct: 'Margin, because margin increases space outside of an element, and that would apply in this scenario.',
        explanation: '',
        questionId: '24003',
        keyword: ['margin', 'padding'],
    },
    {
        question: 'What is HTML?',
        answers: [
            'HTML (HyperText Markup Language) is a markup language that uses tags to structure and define content on web pages.',
            '',
            '',
            '',
        ],
        correct: 'HTML (HyperText Markup Language) is a markup language that uses tags to structure and define content on web pages.',
        explanation: '',
        questionId: '24004',
        keyword: ['HTML'],
    },
    {
        question: 'What are Semantic HTML5 Elements',
        answers: [
            '',
            '',
            'Semantic elements are HTML5 tags that clearly describe their meaning and content purpose to both browsers and developers, like <header>, <main>. <article>. ',
            '',
        ],
        correct: 'Semantic elements are HTML5 tags that clearly describe their meaning and content purpose to both browsers and developers, like <header>, <main>. <article>. ',
        explanation: '',
        questionId: '24005',
        keyword: ['Semantic Elements'],
    },
    {
        question: 'What is the difference between <div> and <section>?',
        answers: [
            '',
            '',
            '',
            '<div> is a generic container with no semantic meaning, while <section> represents a thematic grouping of content with its own heading.',
        ],
        correct: '<div> is a generic container with no semantic meaning, while <section> represents a thematic grouping of content with its own heading.',
        explanation: '',
        questionId: '24006',
        keyword: [''],
    },
    {
        question: 'Why is the label tag important for forms?',
        answers: [
            '',
            '',
            '',
            'The <label> tag creates a programmatic association between description text and form input elements, providing context and improving usability.',
        ],
        correct: 'The <label> tag creates a programmatic association between description text and form input elements, providing context and improving usability.',
        explanation: '',
        questionId: '24007',
        keyword: [''],
    },
    {
        question: 'How do you optimize HTML for performance?',
        answers: [
            '',
            'HTML performance optimization involves structuring markup to reduce page load times, minimize render-blocking resources and improve user experience through efficient code organization.',
            '',
            '',
        ],
        correct: 'HTML performance optimization involves structuring markup to reduce page load times, minimize render-blocking resources and improve user experience through efficient code organization.',
        explanation: '',
        questionId: '24008',
        keyword: [''],
    },
    {
        question: 'What\'s the purpose of "alt" attribute in the <img> tag? ',
        answers: [
            'The "alt" attribute provides alternative text description for images when they cannot be displayed or accessed, serving as a textual replacement for visual content.',
            '',
            '',
            '',
        ],
        correct: 'The "alt" attribute provides alternative text description for images when they cannot be displayed or accessed, serving as a textual replacement for visual content.',
        explanation: '',
        questionId: '24009',
        keyword: [''],
    },
    {
        question: 'When should you use Tables versus other elements?',
        answers: [
            '',
            '',
            '',
            'HTML tables should be used exclusively for displaying tabular data that has meaningful relationships between rows and columns.',
        ],
        correct: 'HTML tables should be used exclusively for displaying tabular data that has meaningful relationships between rows and columns.',
        explanation: '',
        questionId: '24010',
        keyword: [''],
    },
    {
        question: 'HOw does the browswer parse HTML documents?',
        answers: [
            'HTML parsing is the process where browsers convert HTML text into a Document Object Model (DOM) tree that can be rendered and manipulated.',
            '',
            '',
            '',
        ],
        correct: 'HTML parsing is the process where browsers convert HTML text into a Document Object Model (DOM) tree that can be rendered and manipulated.',
        explanation: '',
        questionId: '24011',
        keyword: [''],
    },
    {
        question: 'What is the critical rendering path?',
        answers: [
            '',
            'The critical rendering path is the sequence of steps browsers take to convert HTML, CSS, and JavaScript into rendered pixels on screen.',
            '',
            '',
        ],
        correct: 'The critical rendering path is the sequence of steps browsers take to convert HTML, CSS, and JavaScript into rendered pixels on screen.',
        explanation: '',
        questionId: '24012',
        keyword: [''],
    },
    {
        question: 'What answer best explains form validation attributes and custom validation?',
        answers: [
            '',
            '',
            'HTML5 provides built-in validation attributes like "required", "pattern", "min", and "max" that enable client-side form validation without JavaScript.',
            '',
        ],
        correct: 'HTML5 provides built-in validation attributes like "required", "pattern", "min", and "max" that enable client-side form validation without JavaScript.',
        explanation: '',
        questionId: '24013',
        keyword: [''],
    },
    {
        question: 'What answer best explains data attributes and how they are used effectively?',
        answers: [
            '',
            '',
            '',
            'Data attributes are custom HTML attributes that start with "data-" and allow storing extra information on HTML elements without affecting the element\'s appearance or behavior.',
        ],
        correct: 'Data attributes are custom HTML attributes that start with "data-" and allow storing extra information on HTML elements without affecting the element\'s appearance or behavior.',
        explanation: '',
        questionId: '24014',
        keyword: ['data-attributes'],
    },
    {
        question: 'What is the difference between the <canvas> and <svg> tags?',
        answers: [
            '<canvas> is a raster based drawing surface manipulated with JavaScript, while <svg> is a vector-based graphic defined with XML markup.',
            '',
            '',
            '',
        ],
        correct: '<canvas> is a raster based drawing surface manipulated with JavaScript, while <svg> is a vector-based graphic defined with XML markup.',
        explanation: '',
        questionId: '24015',
        keyword: ['<canvas> tag, <svg> tag'],
    },
    {
        question: 'What does the "srcset" attribute do?',
        answers: [
            '',
            'The "srcset" attribute specifies the URL of the image to use in different situations. The attribute is required when <source> is used in <picture>.',
            '',
            '',
        ],
        correct: 'The "srcset" attribute specifies the URL of the image to use in different situations. The attribute is required when <source> is used in <picture>.',
        explanation: 'The "srcset" property, along with the "sizes" property, are a crucial component in designing responsive websites, as they can be used together to make pages that use appropriate images for the rendering situation.',
        questionId: '24016',
        keyword: ['srcset'],
    },
    {
        question: 'What does the "size" attribute do',
        answers: [
            '',
            '',
            'The "size" attribute defines the width of the <input> and the height of the <select> element.',
            '',
        ],
        correct: 'The "size" attribute defines the width of the <input> and the height of the <select> element.',
        explanation: 'For an input element, it defines the number of characters that the user agent allows the user to see when editing the value. For a select element, it defines the number of options that should be shown to the user. This must be a valid non-negative integer greater than zero.',
        questionId: '24017',
        keyword: ['size attribute'],
    },
    {
        question: '',
        answers: [
            '',
            '',
            '',
            '',
        ],
        correct: '',
        explanation: '',
        questionId: '24018',
        keyword: [''],
    },
    {
        question: '',
        answers: [
            '',
            '',
            '',
            '',
        ],
        correct: '',
        explanation: '',
        questionId: '24019',
        keyword: [''],
    },

];
export default htmlQuestionBank;
// {
//     question: '',
//     answers: [
//         '', 
//         '', 
//         '', 
//         '', 
//     ],
//     correct: '',
//     explanation: '',
//     questionId: '24004',
//     keyword: [''],
// },