import formatImage from '../assets/questionImages/formattedTextImg.jpeg';
import captionImage from '../assets/questionImages/CaptionImage.jpeg';

const htmlQuestionBank = [
    {
        question: 'How do you create the formatted text below?',
        image: formatImage,
        answers: [
            '<p>This is a <mark>Formatted</mark> text</p>',
            '<p>This is a <highlight>Formatted<highlight> text</p>',
            '<p>This is a <color>Formatted</color> text</p>',
            '<p>This is a <em>Formatted</em> text<p>',
        ],
        correct: '<p>This is a <mark>Formatted</mark> text</p>',
        explanation: ' <mark> element is used to highlight or mark text within a document for reference or notation purposes, typically due to its relevance in a specific context. It is semantically equivalent to using a highlighter pen to draw attention to a particular passage in a printed document.',
        questionId: '24000',
        keyword: ['HTML Tags', 'Semantic Tags'],
    },
    {
        question: 'Which group of tags are considered semantic tags',
        answers: [
            '<div>, <span>',
            '<img>, <table>, <article>, <section>, <aside>, <nav>',
        ],
        correct: '<img>, <table>, <article>, <section>, <aside>, <nav>',
        explanation: 'Semantic tags in HTML are elemetnts that clearly define their content\'s purpose and meaing to both the browswer and the developer.',
        questionId: '24001',
        keyword: ['HTML Tags', 'Semantic Tags'],
    },
    {
        question: 'What are semantic tags in HTML',
        answers: [
            'Semantic tags in HTML are tags that don\'t care about the semantics.',
            'Semantic tags are tags like the <div> and <span> tags.',
            'Semantic tags in HTML are elemetnts that clearly define their content\'s purpose and meaing to both the browswer and the developer.',
            'Semantic tags are the tags used to process the inputs of a form.',
        ],
        correct: 'Semantic tags in HTML are elemetnts that clearly define their content\'s purpose and meaing to both the browswer and the developer.',
        explanation: '',
        questionId: '24002',
        keyword: ['HTML Tags', 'Semantic Tags'],
    },

    {
        question: 'There are two divs, they are next to each other, and I need to increase the space between the divs. Would I use margin or padding?',
        answers: [
            'Padding, because padding increases space outside of an element, and that would apply in this scenario.',
            'Margin, because margin increases space outside of an element, and that would apply in this scenario.',
        ],
        correct: 'Margin, because margin increases space outside of an element, and that would apply in this scenario.',
        explanation: '',
        questionId: '24003',
        keyword: ['margin', 'padding'],
    },
    {
        question: 'What is HTML?',
        answers: [
            'HTML (HyperText Markup Language) is a markup language that uses tags to structure and define content on web pages.',
            'HTML (HyperText Mimmic Language) is a programming language exclusively used to create iPhone apps.',
            'HTML (HyperTransit Meduim Language) is a programming language exclusively used to create Android apps.',
            'HTML (HyperTextual Motion Loader) is a programming language exclusively used to create iPhone apps.',
        ],
        correct: 'HTML (HyperText Markup Language) is a markup language that uses tags to structure and define content on web pages.',
        explanation: '',
        questionId: '24004',
        keyword: ['HTML'],
    },
    {
        question: 'What are Semantic HTML5 Elements',
        answers: [
            'Semantic elements in HTML5 are POST, GET, PUSH, DELETE',
            'Semantic elements in HTML5 are elements that allow the frontend of an application to communicate with the backend of an application.',
            'Semantic elements are HTML5 tags that clearly describe their meaning and content purpose to both browsers and developers, like <header>, <main>. <article>. ',
            'Semantic elements are HTML5 tags like <div> and <span>',
        ],
        correct: 'Semantic elements are HTML5 tags that clearly describe their meaning and content purpose to both browsers and developers, like <header>, <main>. <article>. ',
        explanation: '',
        questionId: '24005',
        keyword: ['Semantic Elements'],
    },
    {
        question: 'What is the difference between <div> and <section>?',
        answers: [
            '<div> divides a web page into halves and <section> divides a web page into quarters.',
            'There are no differences between <div> and <section>, the convey the same thing.',
            '<div> represents a thematic grouping of content with its own heading, while <section> is a generic container with no semantic meaning.',
            '<div> is a generic container with no semantic meaning, while <section> represents a thematic grouping of content with its own heading.',
        ],
        correct: '<div> is a generic container with no semantic meaning, while <section> represents a thematic grouping of content with its own heading.',
        explanation: '',
        questionId: '24006',
        keyword: ['HTML elements', 'HTML element basics'],
    },
    {
        question: 'Why is the label tag important for forms?',
        answers: [
            'The <label> tag allows the backend of an application to read the form.',
            'The <label> tag allows the javascript code in an application to access the form\'s content.',
            'The <label> tag is used as a highlighter effect so that users can find a form when a website is in dark mode.',
            'The <label> tag creates a programmatic association between description text and form input elements, providing context and improving usability.',
        ],
        correct: 'The <label> tag creates a programmatic association between description text and form input elements, providing context and improving usability.',
        explanation: '',
        questionId: '24007',
        keyword: ['HTML elements', '<label>'],
    },
    {
        question: 'How do you optimize HTML for performance?',
        answers: [
            'HTML performance optimization can be achieved by wrapping your code with the <optimize> tags, and the code will be automatically optimized.',
            'HTML performance optimization involves structuring markup to reduce page load times, minimize render-blocking resources and improve user experience through efficient code organization.',
            'HTML performance optimization involves removing all photos and videos from your site.',
            'HTML performance optimization can be achieved by not using the <section> tag, the <label> tag, or the <find> tag.',
        ],
        correct: 'HTML performance optimization involves structuring markup to reduce page load times, minimize render-blocking resources and improve user experience through efficient code organization.',
        explanation: 'HTML performance optimization focuses on improving the speed and efficiency of how a web page\'s HTML structure is delivered and rendered by the browser.',
        questionId: '24008',
        keyword: ['HTML optimization'],
    },
    {
        question: 'What\'s the purpose of the "alt" attribute in the <img> tag? ',
        answers: [
            'The "alt" attribute provides alternative text description for images when they cannot be displayed or accessed, serving as a textual replacement for visual content.',
            'The "alt" attribute serves no purpose and was deprecated several years ago.',
            'The "alt" attribute is a custom HTML attributes that start with "alt-" and allow storing extra information on HTML elements without affecting the element\'s appearance or behavior.',
            'The "alt" attribute is a vector-based graphic defined with XML markup.',
        ],
        correct: 'The "alt" attribute provides alternative text description for images when they cannot be displayed or accessed, serving as a textual replacement for visual content.',
        explanation: '',
        questionId: '24009',
        keyword: ['<img> alt attribute'],
    },
    {
        question: 'When should you use Tables versus other elements?',
        answers: [
            '',
            '',
            '',
            'HTML tables should be used exclusively for displaying tabular data that has meaningful relationships between rows and columns.',
        ],
        correct: 'HTML tables should be used exclusively for displaying tabular data that has meaningful relationships between rows and columns.',
        explanation: '',
        questionId: '24010',
        keyword: [''],
    },
    {
        question: 'How does the browswer parse HTML documents?',
        answers: [
            'HTML parsing is the process where browsers convert HTML text into a Document Object Model (DOM) tree that can be rendered and manipulated.',
            '',
            '',
            '',
        ],
        correct: 'HTML parsing is the process where browsers convert HTML text into a Document Object Model (DOM) tree that can be rendered and manipulated.',
        explanation: '',
        questionId: '24011',
        keyword: [''],
    },
    {
        question: 'What is the critical rendering path?',
        answers: [
            '',
            'The critical rendering path is the sequence of steps browsers take to convert HTML, CSS, and JavaScript into rendered pixels on screen.',
            '',
            '',
        ],
        correct: 'The critical rendering path is the sequence of steps browsers take to convert HTML, CSS, and JavaScript into rendered pixels on screen.',
        explanation: '',
        questionId: '24012',
        keyword: [''],
    },
    {
        question: 'What answer best explains form validation attributes and custom validation?',
        answers: [
            '',
            '',
            'HTML5 provides built-in validation attributes like "required", "pattern", "min", and "max" that enable client-side form validation without JavaScript.',
            '',
        ],
        correct: 'HTML5 provides built-in validation attributes like "required", "pattern", "min", and "max" that enable client-side form validation without JavaScript.',
        explanation: '',
        questionId: '24013',
        keyword: [''],
    },
    {
        question: 'What answer best explains data attributes and how they are used effectively?',
        answers: [
            '',
            '',
            '',
            'Data attributes are custom HTML attributes that start with "data-" and allow storing extra information on HTML elements without affecting the element\'s appearance or behavior.',
        ],
        correct: 'Data attributes are custom HTML attributes that start with "data-" and allow storing extra information on HTML elements without affecting the element\'s appearance or behavior.',
        explanation: '',
        questionId: '24014',
        keyword: ['data-attributes'],
    },
    {
        question: 'What is the difference between the <canvas> and <svg> tags?',
        answers: [
            '<canvas> is a raster based drawing surface manipulated with JavaScript, while <svg> is a vector-based graphic defined with XML markup.',
            '',
            '',
            '',
        ],
        correct: '<canvas> is a raster based drawing surface manipulated with JavaScript, while <svg> is a vector-based graphic defined with XML markup.',
        explanation: '',
        questionId: '24015',
        keyword: ['<canvas> tag, <svg> tag'],
    },
    {
        question: 'What does the "srcset" attribute do?',
        answers: [
            '',
            'The "srcset" attribute specifies the URL of the image to use in different situations. The attribute is required when <source> is used in <picture>.',
            '',
            '',
        ],
        correct: 'The "srcset" attribute specifies the URL of the image to use in different situations. The attribute is required when <source> is used in <picture>.',
        explanation: 'The "srcset" property, along with the "sizes" property, are a crucial component in designing responsive websites, as they can be used together to make pages that use appropriate images for the rendering situation.',
        questionId: '24016',
        keyword: ['srcset'],
    },
    {
        question: 'What does the "size" attribute do',
        answers: [
            '',
            '',
            'The "size" attribute defines the width of the <input> and the height of the <select> element.',
            '',
        ],
        correct: 'The "size" attribute defines the width of the <input> and the height of the <select> element.',
        explanation: 'For an input element, it defines the number of characters that the user agent allows the user to see when editing the value. For a select element, it defines the number of options that should be shown to the user. This must be a valid non-negative integer greater than zero.',
        questionId: '24017',
        keyword: ['size attribute'],
    },
    {
        question: 'Which of the following is a Global attribute in HTML?',
        answers: [
            'title',
            'src',
            'href',
            'value',
        ],
        correct: 'title',
        explanation: 'Global attributes in HTML are attributes that can be applied to any HTML element.',
        questionId: '24018',
        keyword: ['global attributes'],
    },
    {
        question: 'In the HTML5 Geolocatoin API, which method is used to return the user\'s location?',
        answers: [
            'getCurrentPosition()',
            'getCurrentLocation()',
            'getuserLocation()',
            'getPosition()',
        ],
        correct: 'getCurrentPosition()',
        explanation: 'getCurrentPosition() returns the device’s latitude, longitude, and other related data once. There is no getCurrentLocation(), getuserLocation(), or getPosition() method in the API.',
        questionId: '24019',
        keyword: ['getCurrentPosition()'],
    },
    {
        question: 'How would you add the "Monthly Savings" caption to the table below?',
        image: captionImage,
        answers: [
            '<table border="1"><caption>Monthly Savings</caption></table>',
            '<table border="1"><title>Monthly Savings</title></table>',
            '<table border="1"><summary>Monthly Savings</summary></table>',
            '<table border="1" caption="Monthly Savings"></table>',
        ],
        correct: '<table border="1"><caption>Monthly Savings</caption></table>',
        explanation: '',
        questionId: '24020',
        keyword: ['HTML Elements'],
    },
    {
        question: 'What are ARIA roles?',
        answers: [
            '',
            '',
            '',
            'ARIA roles provide a way to describe elements that might not be naturally understandable by assistive technologies.',
        ],
        correct: 'ARIA roles provide a way to describe elements that might not be naturally understandable by assistive technologies.',
        explanation: 'ARIA roles help convey the purpose and behavior of elements to assitive technologies, allowing users to understand and interact with web content more effectively.',
        questionId: '24021',
        keyword: ['ARIA roles', 'ARIA properties', 'ARIA states'],
    },
    {
        question: 'Which group of four are key ARIA attributes?',
        answers: [
            'aria-expanded, aria-split, aria-pop(), aria-onclick',
            'aria-labelledby, aria-popleft, aria-forloop, aria-while',
            'aria-haspopup, aria-expanded, aria-labelledby, aria-label',
            'aria-isdigit, aria-stringify, aria-queue, aria-border',
        ],
        correct: 'aria-haspopup, aria-expanded, aria-labelledby, aria-label',
        explanation: 'ARIA supplements HTML so that interactions and widgets commonly used in applications can be passed to assistive technologies when there is not otherwise a mechanism.',
        questionId: '24022',
        keyword: ['ARIA roles', 'ARIA properties', 'ARIA states'],
    },
    {
        question: 'Which answer best describes keyboard navigation accessibility?',
        answers: [
            'Keyboard naviation accessibility is not a real thing in development.',
            'Keyboard naviation accessibility ensures all interactive elements can be operated using only the keyboard.',
            'Keyboard naviation accessibility allows the keyboard access to private JavaScript functions.',
            'Keyboard naviation accessibility makes CSS files accessible to your JavaScript code.',
        ],
        correct: 'Keyboard naviation accessibility ensures all interactive elements can be operated using only the keyboard.',
        explanation: 'Keyboard accessibility is one of the most important aspects of web accessibility. Many users with motor disabilities rely on a keyboard.',
        questionId: '24023',
        keyword: ['Keyboard accessibility'],
    },
    {
        question: 'What are Open Graph tags?',
        answers: [
            'Open Graph tags are HTML tags that allow you to control how your content is presented when shared on social media.',
            '',
            '',
            '',
        ],
        correct: 'Open Graph tags are HTML tags that allow you to control how your content is presented when shared on social media.',
        explanation: 'Open Graph tags provide a way to customize how your content appears when shared on social media. They specify the title, description, image, site name, and other information that you want to be shown for a shared piece of content.',
        questionId: '24024',
        keyword: ['Open Graph tags'],
    },
    {
        question: 'What are Twitter meta card tags?',
        answers: [
            '',
            '',
            'Twitter meta card tags are a set of HTML meta tags that allow website owners to control how their content appears when shared on Twitter.',
            '',
        ],
        correct: 'Twitter meta card tags are a set of HTML meta tags that allow website owners to control how their content appears when shared on Twitter.',
        explanation: '',
        questionId: '24025',
        keyword: ['Twitter meta card'],
    },
    {
        question: 'Which of the following methods can be used in the HTML5 drag and drop API?',
        answers: [
            'onDragBegin()',
            'onDragStart()',
            'onDragFinish()',
            'onDragEnding()',
        ],
        correct: 'onDragStart()',
        explanation: '',
        questionId: '24026',
        keyword: ['HTML5 drag and drop API', 'onDragStart()', 'onDragEnd()'],
    },
    {
        question: 'How do you ensure that the href is loaded in a new tab when the link is clicked.',
        answers: [
            '<a href="https://paulrblack.com/" target="_blank"><Interview Prep/a> is a platform to test candidates before hiring',
            '<a href="https://paulrblack.com/" target="_newtab"><Interview Prep/a> is a platform to test candidates before hiring',
            '<a href="https://paulrblack.com/" target="_new">Interview Prep</a> is a platform to test candidates before hiring',
            '<a href="https://paulrblack.com/" target="_nt">Interview Prep</a> is a platform to test candidates before hiring',
        ],
        correct: '<a href="https://paulrblack.com/" target="_blank"><Interview Prep/a> is a platform to test candidates before hiring',
        explanation: 'This value instructs the browser to open the linked document in a new window or tab. This is often used when linking to external websites or documents that the user might want to view separately without navigating away from the current page',
        questionId: '24027',
        keyword: ['_blank'],
    },
    {
        question: 'Which of the following can be used to draw a rectangle?',
        answers: [
            '<canvas>',
            '<rectangle>',
            '<shape>',
            '<container>',
        ],
        correct: '<canvas>',
        explanation: 'The HTML <canvas> element is used to draw graphics, on the fly, via JavaScript. Canvas has several methods for drawing paths, boxes, circles, text, and adding images like, <canvas id="myCanvas" width="200" height="100" style="border:1px solid #000000;"></canvas>',
        questionId: '24028',
        keyword: ['HTML elements', '<canvas>'],
    },
    {
        question: 'How do you implement structured data with HTML?',
        answers: [
            '<canvas>',
            '<rectangle>',
            '<shape>',
            '<container>',
        ],
        correct: '<canvas>',
        explanation: 'The HTML <canvas> element is used to draw graphics, on the fly, via JavaScript. Canvas has several methods for drawing paths, boxes, circles, text, and adding images like, <canvas id="myCanvas" width="200" height="100" style="border:1px solid #000000;"></canvas>',
        questionId: '24028',
        keyword: ['HTML elements', '<canvas>'],
    },
    {
        question: 'What is "structured data" in HTML?',
        answers: [
            '',
            '',
            '',
            'structured data is extra information embedded in HTML so that search engines can better understand the cnotent of a web page.',
        ],
        correct: 'structured data is extra information embedded in HTML so that search engines can better understand the cnotent of a web page.',
        explanation: 'structured data isn\'t about how the page looks to users — is about giving machines context.',
        questionId: '24029',
        keyword: ['schema.org', 'semantic HTML', 'web SEO'],
    },
    {
        question: 'What are Web Components',
        answers: [
            'Web Components are a set of web platform APIs that allow for the creaton of custom, reusable HTML elements with encapsulated functionallity and styling.',
            '',
            '',
            '',
        ],
        correct: 'Web Components are a set of web platform APIs that allow for the creaton of custom, reusable HTML elements with encapsulated functionallity and styling.',
        explanation: 'In essence, Web Components allow you to create self-contained UI components with their own logic, styling, and markup, which can then be easily integrated and reused in any web application, promoting better organization, reusability, and maintainability of web projects',
        questionId: '24030',
        keyword: ['Web Components'],
    },
    {
        question: 'What is Lazy Loading?',
        answers: [
            '',
            'Lazy loading is a strategy to identify resources as non-blocking (non-critical) and load these only when needed.',
            '',
            '',
        ],
        correct: 'Lazy loading is a strategy to identify resources as non-blocking (non-critical) and load these only when needed.',
        explanation: 'It\'s a way to shorten the length of the critical rendering path, which translates into reduced page load times',
        questionId: '24031',
        keyword: ['lazy loading', 'critical rendering path'],
    },
    {
        question: 'Which of the answers correctly implements lazy loading on the image tag?',
        answers: [
            '<img src="https://media.batslignal.jpg" alt="numbers load="lazily"/>',
            '<img src="https://media.batslignal.jpg" alt="numbers loading="load-lazy"/>',
            '<img src="https://media.batslignal.jpg" alt="numbers loading="lazy"/>',
            '<img src="https://media.batslignal.jpg" alt="numbers load="lazy-load"/>',
        ],
        correct: '<img src="https://media.batslignal.jpg" alt="numbers loading="lazy"/>',
        explanation: '',
        questionId: '24032',
        keyword: ['lazy loading'],
    },
    {
        question: 'HTML provides a native way to create modal without the need for JavaScript, which elemnt would you use to create a modal?',
        answers: [
            '<htmodal>',
            '<modal>',
            '<dialog>',
            '<popup>',
        ],
        correct: '<dialog>',
        explanation: 'The HTML <dialog> element is used to create both modal and non-modal dialog boxes. Modal dialog boxes interrupt interaction with the rest of the page being inert, while non-modal dialog boxes allow interaction with the rest of the page.',
        questionId: '24033',
        keyword: ['<dialog>'],
    },
    {
        question: 'Which best describes Progressive Web Apps (PWA)?',
        answers: [
            '',
            '',
            '',
            'A progressive web app (PWA) is an app that\'s built using web platform technologies, but that provides a user experience like that of a platform-specific app.',
        ],
        correct: 'A progressive web app (PWA) is an app that\'s built using web platform technologies, but that provides a user experience like that of a platform-specific app.',
        explanation: 'Like a website, a PWA can run on multiple platforms and devices from a single codebase. Like a platform-specific app, it can be installed on the device, can operate while offline and in the background, and can integrate with the device and with other installed apps.',
        questionId: '24034',
        keyword: ['(Progressive web apps PWA)'],
    },
    {
        question: 'What is an attribute in HTML?',
        answers: [
            'An attribute is additional information provided inside a tag, which modifies the tag\'s behavior.',
            '',
            '',
            '',
        ],
        correct: 'An attribute is additional information provided inside a tag, which modifies the tag\'s behavior.',
        explanation: '',
        questionId: '24035',
        keyword: ['HTML attributes'],
    },
    {
        question: 'Progressive Web Apps are...',
        answers: [
            '',
            'Web applications taht use modern web technologies to provide a fast, reliable and engaging user experience.',
            '',
            '',
        ],
        correct: 'Web applications taht use modern web technologies to provide a fast, reliable and engaging user experience.',
        explanation: '',
        questionId: '24036',
        keyword: [''],
    },


];
export default htmlQuestionBank;


// {
//     question: '',
//     answers: [
//         '', 
//         '', 
//         '', 
//         '', 
//     ],
//     correct: '',
//     explanation: '',
//     questionId: '24004',
//     keyword: [''],
// },


