const restAPIQuestionBank = [
    {
        question: 'How are REST APIs stateless?',
        answers: [
            '',
            '',
            '',
            '',
        ],
        correct: '',
        explanation: '',
        questionId: '25000',
        keyword: ['', ''],
    },
    {
        question: 'What are the HTTP methods?',
        answers: [
            'SEARCH, SHOW, TRASH',
            'FOR, WHILE, IF',
            'GET, POST, PUT, DELETE',
            'DIV, INPUT, BUTTON, H1',
        ],
        correct: 'GET, POST, PUT, DELETE',
        explanation: '',
        questionId: '25001',
        keyword: ['http methods'],
    },
    {
        question: 'What does the GET Http method do?',
        answers: [
            '',
            '',
            '',
            'GET fetches a resource from the server',
        ],
        correct: 'GET fetches a resource from the server',
        explanation: '',
        questionId: '25002',
        keyword: ['http methods', 'GET method'],
    },
    {
        question: 'What does the POST Http method do?',
        answers: [
            'POST requests for a resource to be created on the server',
            '',
            '',
            '',
        ],
        correct: 'POST requests for a resource to be created on the server',
        explanation: '',
        questionId: '25003',
        keyword: ['http methods', 'POST method'],
    },
    {
        question: 'What does the PUT Http method do?',
        answers: [
            '',
            'PUT requests for a resource to be updated',
            '',
            '',
        ],
        correct: 'PUT requests for a resource to be updated',
        explanation: '',
        questionId: '25004',
        keyword: ['http methods', 'PUT method'],
    },
    {
        question: 'What does the DELETE Http method do?',
        answers: [
            '',
            '',
            '',
            'DELETE requests for a resource to be deleted',
        ],
        correct: 'DELETE requests for a resource to be deleted',
        explanation: '',
        questionId: '25005',
        keyword: ['http methods', 'DELETE method'],
    },
    {
        question: 'What are Http status codes?',
        answers: [
            '',
            '',
            '',
            '',
        ],
        correct: '',
        explanation: '',
        questionId: '25006',
        keyword: ['status codes', ''],
    },
    {
        question: 'What does a status code in the 200s represent?',
        answers: [
            'A status code in the 200s represent a successful request and response',
            'A status code in the 200s represent a server-side error',
            'A status code in the 200s represents a user error',
            'A status code in the 200s represents a broken internet connection',
        ],
        correct: 'A status code in the 200s represent a successful request and response',
        explanation: '',
        questionId: '25007',
        keyword: ['status codes'],
    },
    {
        question: 'What does a status code in the 400s represent?',
        answers: [
            'A status code in the 400s represents a slow internet speed',
            'A status code in the 400s represent a server-side error',
            'A status code in the 400s represent a successful request and response',
            'A status code in the 400s represents a client side error',
        ],
        correct: 'A status code in the 400s represents a client side error',
        explanation: '',
        questionId: '25008',
        keyword: ['status codes'],
    },
    {
        question: 'What does a status code in the 500s represent?',
        answers: [
            'A status code in the 500s represents a client side error',
            'A status code in the 500s represent a server-side error',
            'A status code in the 400s represent a successful request and response',
            'A status code in the 400s represents a slow internet speed',
        ],
        correct: 'A status code in the 500s represent a server-side error',
        explanation: '',
        questionId: '25009',
        keyword: ['status codes'],
    },
    {
        question: 'What does URI stand for?',
        answers: [
            'Unintended Request Initiator',
            'Uninformed Resource Identification',
            'United Resources Initiated',
            'Uniform Resource Identifier',
        ],
        correct: 'Uniform Resource Identifier',
        explanation: '',
        questionId: '25010',
        keyword: ['URI'],
    },
    {
        question: 'What is a URI?',
        answers: [
            'URIs identify every resource in the rest architecture.',
            '',
            '',
            '',
        ],
        correct: 'URIs identify every resource in the rest architecture.',
        explanation: '',
        questionId: '25011',
        keyword: ['URI'],
    },
    {
        question: 'What are the two types of URIs?',
        answers: [
            'URN and URL',
            'PUT and PATCH',
            'GET and DELETE',
            'ECHO and CURL',
        ],
        correct: 'URN and URL',
        explanation: '',
        questionId: '25012',
        keyword: ['URI'],
    },
    {
        question: 'What are the differences between REST and SOAP',
        answers: [
            '',
            '',
            '',
            '',
        ],
        correct: '',
        explanation: '',
        questionId: '25013',
        keyword: ['', ''],
    },
    {
        question: 'What does SOAP stand for?',
        answers: [
            'Simple Object Access Protocol',
            'Success Obtained After Put',
            'Simple Outlier Architechture Protocol',
            'Search Out Active Processing',
        ],
        correct: 'Simple Object Access Protocol',
        explanation: '',
        questionId: '25014',
        keyword: ['SOAP', 'REST'],
    },
    {
        question: 'What does API stand for?',
        answers: [
            '',
            '',
            '',
            '',
        ],
        correct: '',
        explanation: '',
        questionId: '25015',
        keyword: ['', ''],
    },
    {
        question: 'When it comes to data transfers, SOAP supports',
        answers: [
            'JSON, XML, and YAML',
            'JSON only',
            'XML only',
            'YAML only',
        ],
        correct: 'XML only',
        explanation: '',
        questionId: '25016',
        keyword: ['', ''],
    },
    {
        question: 'SOAP is considered a stricture and more niche alternative to REST?',
        answers: [
            'True',
            'False',
        ],
        correct: 'True',
        explanation: '',
        questionId: '25017',
        keyword: ['SOAP', 'REST'],
    },
    {
        question: 'What is the difference between REST and AJAX?',
        answers: [
            '',
            '',
            '',
            '',
        ],
        correct: '',
        explanation: '',
        questionId: '25018',
        keyword: ['', ''],
    },
    {
        question: 'What does AJAX stand for?',
        answers: [
            '',
            '',
            '',
            'Asynchronous Javascript and XML',
        ],
        correct: 'Asynchronous Javascript and XML',
        explanation: '',
        questionId: '25019',
        keyword: ['', ''],
    },
    {
        question: '',
        answers: [
            '',
            '',
            '',
            '',
        ],
        correct: '',
        explanation: '',
        questionId: '25020',
        keyword: ['', ''],
    },
    {
        question: '',
        answers: [
            '',
            '',
            '',
            '',
        ],
        correct: '',
        explanation: '',
        questionId: '25021',
        keyword: ['', ''],
    },
    {
        question: '',
        answers: [
            '',
            '',
            '',
            '',
        ],
        correct: '',
        explanation: '',
        questionId: '25022',
        keyword: ['', ''],
    },
    {
        question: '',
        answers: [
            '',
            '',
            '',
            '',
        ],
        correct: '',
        explanation: '',
        questionId: '25021',
        keyword: ['', ''],
    },
    {
        question: '',
        answers: [
            '',
            '',
            '',
            '',
        ],
        correct: '',
        explanation: '',
        questionId: '25022',
        keyword: ['', ''],
    },
    {
        question: '',
        answers: [
            '',
            '',
            '',
            '',
        ],
        correct: '',
        explanation: '',
        questionId: '25021',
        keyword: ['', ''],
    },
    {
        question: '',
        answers: [
            '',
            '',
            '',
            '',
        ],
        correct: '',
        explanation: '',
        questionId: '25022',
        keyword: ['', ''],
    },
    {
        question: '',
        answers: [
            '',
            '',
            '',
            '',
        ],
        correct: '',
        explanation: '',
        questionId: '25021',
        keyword: ['', ''],
    },
    {
        question: '',
        answers: [
            '',
            '',
            '',
            '',
        ],
        correct: '',
        explanation: '',
        questionId: '25022',
        keyword: ['', ''],
    },
]